version: "3"

services:
  db_postgres:
    image: postgres:13.2
    restart: always
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  django_app:
    build: 
        context: .
        dockerfile: Dockerfile
    ports:
        - 8000:8000
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static:/code/static
      - .:/code
    depends_on:
      - db_postgres
    
volumes:
  .:
  postgres_data:
  static:
