# Generated by Django 3.2 on 2021-04-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_auto_20210427_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='casa',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
